from os import path, environ
from os.path import dirname, join

from modules.logging import error, debug

PROJECT_DIR = dirname(dirname(dirname(path.abspath(__file__)))) # path to "gateway" folder
GATEWAY_DATA_PATH = str(environ.get("TEG_DATA_PATH") or PROJECT_DIR)
CONTROLLER_DATA_PATH = str(environ.get("TEG_CONTROLLER_DATA_PATH") or GATEWAY_DATA_PATH)
CONTROLLER_LOGS_PATH = str(environ.get("TEG_CONTROLLER_LOGS_PATH") or join(CONTROLLER_DATA_PATH, "logs"))
CONTROLLER_GIT_PATH = str(environ.get("TEG_CONTROLLER_GIT_PATH") or "UNKNOWN")
CONTROLLER_DOCKERCONTEXT_PATH = str(environ.get("TEG_CONTROLLER_DOCKERCONTEXT_PATH") or join(dirname(CONTROLLER_GIT_PATH), "docker"))
CONTROLLER_DOCKERFILE_PATH = str(environ.get("TEG_CONTROLLER_DOCKERFILE_PATH") or "./Dockerfile")

GATEWAY_LOGS_BUFFER_DB_NAME = "gateway_logs_buffer.db"
GATEWAY_LOGS_BUFFER_DB_PATH = join(str(GATEWAY_DATA_PATH), GATEWAY_LOGS_BUFFER_DB_NAME)

GATEWAY_ARCHIVE_DB_NAME = "gateway_archive.db"
GATEWAY_ARCHIVE_DB_PATH = join(str(GATEWAY_DATA_PATH), GATEWAY_ARCHIVE_DB_NAME)

COMMUNICATION_QUEUE_DB_NAME = "communication_queue.db"
COMMUNICATION_QUEUE_DB_PATH = join(str(CONTROLLER_DATA_PATH), COMMUNICATION_QUEUE_DB_NAME)

if CONTROLLER_GIT_PATH == "UNKNOWN":
    error("[FATAL_ERROR] Env var TEG_CONTROLLER_GIT_PATH not set!")

debug(f'PROJECT_DIR: {PROJECT_DIR}')
debug(f'GATEWAY_DATA_PATH: {GATEWAY_DATA_PATH}')
debug(f'CONTROLLER_LOGS_PATH: {CONTROLLER_LOGS_PATH}')
debug(f'CONTROLLER_GIT_PATH: {CONTROLLER_GIT_PATH}')

debug(f'GATEWAY_LOGS_BUFFER_DB_PATH: {GATEWAY_LOGS_BUFFER_DB_PATH}')
debug(f'GATEWAY_ARCHIVE_DB_PATH: {GATEWAY_ARCHIVE_DB_PATH}')
debug(f'COMMUNICATION_QUEUE_DB_PATH: {COMMUNICATION_QUEUE_DB_PATH}')